### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by kinlane** [api-commons/api-json#100]
Add an access property with internal, 1st-party, and 3rd-party as enums.

**Comment by kinlane** [comment]
```
  access:
    type: string
    description: The access level for the APIs in an APIs.json.
    enum:
      - Internal
      - 1st-Party
      - 3rd-Party 
```
