### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by kinlane** [api-commons/api-json#101]
Add a position property with producer and consumer as the enum.

**Comment by kinlane** [comment]
```
  position:
    type: string
    description: The position of the maintainer of APIs.json.
    enum:
      - Producer
      - Consumer 
 ```
